default: &default
  adapter: postgresql
  encoding: UTF8
  database: litenodes
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_MASTER") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_MASTER") %>